### PR TITLE
add student, course and account interfaces

### PR DESCRIPTION
**Pull request by Steve3029**

### CODE REVIEW

**Comment by jerry6789** [comment]
I am not sure if common CRUD should be inside the business layer because somebody told me more sophisticated logic instead of CRUD should be inside the business layer when I asked in StackOverflow and when I made some MVC demo I remembered  CRUD should be in the controller.

Essentially these days I am always confused about what is the business layer and what to do in this layer.

I've learned the MVC pattern but when I saw the file structure of the project I knew it's not simple MVC  so I googled and got this is a 3-tier architecture and the whole MVC should be inside the web folder (Presentation tier) but I still don't know what should be done in the business layer.

**Comment by Steve3029** [comment]
Yes, MVC is traditional web app model, but I don't think MVC is a good fit for LMS. Because we divided the entire application into two separate parts -- front-end and back-end. It means that we do not use controller any more, and all business logic will be working behind Web APIs.

**Comment by jerry6789** [comment]
Yes, you're right and I got what you said.  

I used to think about it like you but I am not sure if it is right, so I asked a dev friend and he told me something like Student entity class, IStudentRepository interface, and interface implement class should be included in the Model layer and what to do in the business layer depends on specific business scenario. 

So, Should we implement Web APIs in the business layer?

**Comment by unruledboy** [comment]
Regarding the interface / layering etc, please watch the videos in Dev Yeah's real-life course. It should answer your concerns

**Pull request merged**
