### PR TITLE
add Level column into Course table and update SQL script to make it c…

### PR DESCRIPTION
**Pull request by Steve3029**
There are two updates：
1. Add a new column -- 'Level' to Course table.
2. Update database initial script to make it could be executed repeatedly.

### CODE REVIEW

**Comment by unruledboy** [comment]
It is strongly NOT recommended to drop existing table.

Please consider: if there are already data in the table, you will LOSE THE DATA.

**Comment by unruledboy** [comment]
To verify if a table already exists, do like this:

IF NOT EXISTS (SELECT NULL FROM sys.tables WHERE name = 'YOUR_TABLE_NAME_HERE')
  --CREATE TABLE

**Comment by unruledboy** [comment]
To verify if other type of object already exists, do like this:

IF NOT EXISTS (SELECT NULL FROM sys.objects WHERE name = 'YOUR_OBJECT_NAME_HERE')
--CREATE 0BJECT

**Comment by unruledboy** [comment]
To verify if column already exists in a table, do like this:

IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'YOUR_TABLE_HERE' AND COLUMN_NAME = 'YOUR_COLUMN_HERE')
   --Use column

**Comment by unruledboy** [comment]
What is the dictionary for Level column? like:

- 1: Foundation
- 2: Entry
- 3: Mid
- 4: Advanced

**Comment by jerry6789** [comment]
I googled INFORMATION_SCHEMA.COLUMNS and then found some IMPORTANT tips about it in MSDN.

I don't understand these tips completely, but is the following code better?

IF (COLUMNPROPERTY(OBJECT_ID(TABLE_SCHEMA + '.' + TABLE_NAME), COLUMN_NAME, 'ColumnID') IS NULL)
BEGIN
--todo
END

https://docs.microsoft.com/en-us/sql/relational-databases/system-information-schema-views/columns-transact-sql?view=sql-server-2017

**Comment by unruledboy** [comment]
@jerry6789 first, your query is not complete. It should use INFORMATION_SCHEMA.COLUMNS  view. Second, we only need to verify if a column exist, it does not need to consider the remarks on msdn, it is a different matter.

**Comment by jerry6789** [comment]
ok, I got it. thx!

**Pull request merged**
